# Module manifest for module 'toggle-faststartup'
# Generated by: MrDwarf7
# Generated on: 30/06/2025

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = 'toggle-faststartup.ps1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # ID used to uniquely identify this module
    GUID = '054de4f9-083e-4546-a190-8ff56558eed3'

    # Author of this module
    Author = 'MrDwarf7'

    # Copyright statement for this module
    Copyright = '(c) MrDwarf7. All rights reserved.'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    ## Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @(
        'toggle-faststartup.ps1'
    )

    # ModuleToProcess = @(
    # )

    # NestedModules = @(
    # )

    # ModuleList = @(
    # )

    # FileList = @(
    # )


    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = '*'

}

